// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/trip/trip.proto

package trip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{0}
}

func (x *GetTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripResponse) Reset() {
	*x = GetTripResponse{}
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripResponse) ProtoMessage() {}

func (x *GetTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripResponse.ProtoReflect.Descriptor instead.
func (*GetTripResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{1}
}

func (x *GetTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *GetTripResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_trip_trip_proto protoreflect.FileDescriptor

const file_proto_trip_trip_proto_rawDesc = "" +
	"\n" +
	"\x15proto/trip/trip.proto\x12\x04trip\")\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"B\n" +
	"\x0fGetTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2E\n" +
	"\vTripService\x126\n" +
	"\aGetTrip\x12\x14.trip.GetTripRequest\x1a\x15.trip.GetTripResponseB8Z6github.com/shemanto27/GoRideSharing/backend/proto/tripb\x06proto3"

var (
	file_proto_trip_trip_proto_rawDescOnce sync.Once
	file_proto_trip_trip_proto_rawDescData []byte
)

func file_proto_trip_trip_proto_rawDescGZIP() []byte {
	file_proto_trip_trip_proto_rawDescOnce.Do(func() {
		file_proto_trip_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)))
	})
	return file_proto_trip_trip_proto_rawDescData
}

var file_proto_trip_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trip_trip_proto_goTypes = []any{
	(*GetTripRequest)(nil),  // 0: trip.GetTripRequest
	(*GetTripResponse)(nil), // 1: trip.GetTripResponse
}
var file_proto_trip_trip_proto_depIdxs = []int32{
	0, // 0: trip.TripService.GetTrip:input_type -> trip.GetTripRequest
	1, // 1: trip.TripService.GetTrip:output_type -> trip.GetTripResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trip_trip_proto_init() }
func file_proto_trip_trip_proto_init() {
	if File_proto_trip_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trip_trip_proto_goTypes,
		DependencyIndexes: file_proto_trip_trip_proto_depIdxs,
		MessageInfos:      file_proto_trip_trip_proto_msgTypes,
	}.Build()
	File_proto_trip_trip_proto = out.File
	file_proto_trip_trip_proto_goTypes = nil
	file_proto_trip_trip_proto_depIdxs = nil
}
